version: "3.8"
services:
  app:
    image: galahade/future-trading-dev:latest
    deploy:
      restart_policy:
        delay: 600s
    working_dir: /app
    volumes:
      # - ".:/app"
      - future-trading-log-data:/log
    depends_on:
      - mongo_db
    networks:
      - database
    environment:
      SYSTEM_CONFIG_PATH: /run/secrets/system_config_file
      FUTURE_CONFIG_PATH: /run/secrets/future_config_file
      ENV_NAME: dev
      # 天勤云账号的子账号数，可以使不同运行环境相互独立测试
      TQKQ_NUMBER: 1
    secrets:
      - system_config_file
      - future_config_file

  mongo_db:
    image: mongo
    networks:
      - database
    ports:
      - 26017:27017
    volumes:
      - future-trading-mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
volumes:
  future-trading-mongo-data:
  future-trading-log-data:
      external: true
networks:
  database:
    attachable: true
secrets:
  system_config_file:
    file: secrets/system_config_dev.yaml
  future_config_file:
    file: conf/trade_config_dev.yaml