version: "3.8"
services:
  app:
    image: galahade/future-trading-dev:v2.0
    deploy:
      restart_policy:
        delay: 1800s
    working_dir: /app
    volumes:
      - ".:/app"
      - future-trading-log-data:/log
    environment:
      SYSTEM_CONFIG_PATH: /run/secrets/system_config_file
      FUTURE_CONFIG_PATH: /run/secrets/future_config_file
      ENV_NAME: dev
      # 天勤云账号的子账号数，可以使不同运行环境相互独立测试
      TQKQ_NUMBER: 1
    secrets:
      - system_config_file
      - future_config_file

volumes:
  future-trading-log-data:
    external: true
secrets:
  system_config_file:
    file: secrets/system_config_dev.yaml
  future_config_file:
    file: conf/trade_config_dev.yaml