version: "3.8"
services:
  app:
    image: galahade/future-trading-dev:latest
    working_dir: /app
    volumes:
      - ".:/app"
      - future-trading-log-data:/log
    environment:
      SYSTEM_CONFIG_PATH: /run/secrets/system_config_file
      FUTURE_CONFIG_PATH: /run/secrets/future_config_file
      ENV_NAME: dev
    secrets:
      - system_config_file
      - future_config_file
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.ft-corn.schedule: "0 30 19 * * *"
      ofelia.job-exec.ft-corn.command: "/docker-entrypoint.sh"

  ofelia:
    image: mcuadros/ofelia:latest
    depends_on:
      - app
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TZ=Asia/Shanghai

volumes:
  future-trading-log-data:
    external: true
secrets:
  system_config_file:
    file: secrets/system_config_dev.yaml
  future_config_file:
    file: conf/trade_config_dev.yaml