version: 1
formatters:
  brief:
    format: '%(levelname)-8s %(name)-15s %(message)s'
  precise:
    format: '%(asctime)s %(levelname)-8s %(name)-15s %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: precise
    stream: ext://sys.stdout
  file:
    class: logging.handlers.TimedRotatingFileHandler
    level: DEBUG
    formatter: precise
    filename: /log/ft_backtest.log
    when: D
    backupCount: 10
    atTime: 15:30
    encoding: utf-8
loggers:
  __main__:
    level: DEBUG
    handlers: [console, file]
    propagate: 0
  TqApi:
    level: WARNING
    handlers: [file]
    propagate: 0
  websockets:
    level: WARNING
    handlers: [file]
    propagate: 0
root:
  level: DEBUG
  handlers: [console, file]
